ecommerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from django.urls import path
from .views import ProductList, ProductDetail

app_name = 'product'
urlpatterns = [
    path('', ProductList.as_view(), name='list'),
    path('details/<int:pk>', ProductDetail.as_view(), name='detail')
]

product/models.py
from django.db import models
from django.urls import reverse_lazy


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=1024)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.CharField(max_length=255, help_text='image url')

    def __str__(self):
        return self.name

    @property
    def get_absolute_url(self):
        return reverse_lazy('product:detail', args=[int(self.pk)])

user/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _


# from django.utils import timezone


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, first_name, last_name, **other):
        """
        Create and save user with given first name, last name and email
        """
        if not (email or password or first_name or last_name):
            raise ValueError('Email, Password, First Name and Last Name are required field!!')
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, **other)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, first_name=None, last_name=None, password=None, **other):
        other.setdefault('is_superuser', False)
        other.setdefault('is_staff', False)

    def create_superuser(self, email=None, password=None, first_name=None, last_name=None, **other):
        """
        Create a superuser
        give some default permissions
        """

        other.setdefault('is_superuser', True)
        other.setdefault('is_staff', True)

        if other.get('is_superuser') is not True:
            raise ValueError('Superuser must be is_superuser')
        elif other.get('is_staff') is not True:
            raise ValueError('Superuser must be is_staff')

        return self._create_user(email, password, first_name, last_name, **other)


class User(AbstractBaseUser, PermissionsMixin):
    """
    Django custom user model
    AbstructBaseUser: Defines the properties required for user mode;
    PermissionMixin: Have some methods to check or set permissions
    """

    email = models.EmailField(_('email'), max_length=128, unique=True, error_messages={
        'unique': _("A user with that username already exists."),
    })
    first_name = models.CharField(_('first name'), max_length=50)
    last_name = models.CharField(_('last name'), max_length=80)

    date_joined = models.DateTimeField(auto_now_add=True)

    # staff user can access admin panel
    is_staff = models.BooleanField(_('is staff'), default=False)
    is_active = models.BooleanField(_('user is active'), default=True, help_text='Don\'t delete user, set False')

    # password and last_login is defined in AbstructBaseUser

    REQUIRED_FIELDS = ['first_name', 'last_name']

    USERNAME_FIELD = 'email'

    objects = UserManager()

    def __str__(self):
        return self.email

product/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Product


class ProductList(ListView):
    model = Product
    template_name = 'product/list.html'
    context_object_name = 'product_list'


class ProductDetail(DetailView):
    model = Product
    template_name = 'product/details.html'
    context_object_name = 'product'

user/views.py
from django.shortcuts import render

# Create your views here.

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Django ecommerce</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/styles.min.css' %}">
</head>

<body class="text-center">
    <nav class="navbar navbar-light navbar-expand-sm sticky-top bg-white text-center border rounded-0 shadow navigation-clean-button">
        <div class="container-fluid"><a class="navbar-brand" href="{% url 'product:list' %}">Company Name</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav mr-auto"></ul><span class="navbar-text actions"> <a class="login" href="#">Log In</a><a class="btn btn-light action-button" role="button" href="#">Sign Up</a></span>
            </div>
            <header></header>
        </div>
    </nav>
    <div class="main">
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer-basic">
        <footer>
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">Company Name © 2017</p>
        </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.3/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'assets/js/script.min.js' %}"></script>
</body>

</html>

templates/product/details.html
{% extends 'index.html' %}
{% block content %}
     <div class="container">
     {% if product %}
        <div class="card" style="margin-top: 12px;"><img class="card-img-top w-100 d-block" src="{{ product.image }}">
            <div class="card-body">
                <h4 class="card-title">{{ product.name }}</h4>
                <p class="card-text">{{ product.description }}</p>
                <div class="btn-group" role="group"><button class="btn btn-warning" type="button">Add to Cart</button></div>
            </div>
        </div>
     {% endif %}
    </div>
{% endblock %}

templates/product/list.html
{% extends 'index.html' %}
{% block content %}
    <div data-bs-parallax-bg="true"
         style="height:500px;background-image:url(https://unsplash.it/1800/900?image=1051);background-position:center;background-size:cover;"></div>

    <div class="article-list">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Latest Articles</h2>
                <p class="text-center">Nunc luctus in metus eget fringilla. Aliquam sed justo ligula. Vestibulum nibh
                    erat, pellentesque ut laoreet vitae. </p>
            </div>
            <div class="row articles">
                {% for product in product_list %}
                    <div class="col-sm-6 col-md-4 item"><a href="{{ product.get_absolute_url }}">
                        <img class="img-fluid" src="{{ product.image }}"></a>
                        <h3 class="name">{{ product.name }}</h3>
                        <p class="description">{{ product.description | truncatewords:30 }}</p>
                        <div class="btn-group shadow" role="group" style="padding-top: 5px;">
                            <button class="btn btn-warning" type="button">Add to Cart</button>
                        </div>
                        <a class="action" href="#"></a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}